[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         http
    Listen       0.0.0.0
    Port         24224
    Tag          banking.core

[OUTPUT]
    Name         stdout
    Match        *
