server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-management-api
          uri: ${BANKING_USER_API_URI:http://localhost:8081}
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: account-banking-api
          uri: ${BANKING_ACCOUNT_API_URI:http://localhost:8082}
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=1
        - id: core-banking-api
          uri: ${BANKING_CORE_API_URI:http://localhost:8083}
          predicates:
            - Path=/api/operations/**
          filters:
            - StripPrefix=1

banking:
  gateway:
    traffic-store-mode: ${BANKING_GATEWAY_TRAFFIC_STORE_MODE:IN_MEMORY}
    users-budget-per-minute: 120
    accounts-budget-per-minute: 60
    operations-budget-per-minute: 30
    default-budget-per-minute: 180
    provider:
      name: ${BANKING_GATEWAY_PROVIDER_NAME:local-provider}
      issuer: ${BANKING_GATEWAY_PROVIDER_ISSUER:local-issuer}
      keys-path: ${BANKING_GATEWAY_PROVIDER_KEYS_PATH:/keys}
      audience: ${BANKING_GATEWAY_PROVIDER_AUDIENCE:banking-api-gateway}

management:
  endpoints:
    web:
      exposure:
        include: health,info
