server:
  port: 8082

spring:
  application:
    name: account-banking-api
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
