server:
  port: 8083

spring:
  application:
    name: core-banking-api
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: core_schema
  flyway:
    enabled: true
    schemas: core_schema
    default-schema: core_schema

banking:
  account-api:
    base-url: http://localhost:8082
    connect-timeout: 1s
    read-timeout: 2s
  observability-api:
    base-url: http://localhost:8085
    connect-timeout: 1s
    read-timeout: 2s

management:
  endpoints:
    web:
      exposure:
        include: health,info
